## 1. Data loading

In [1]:
import pandas as pd
df = pd.read_csv("data/integrated_features_and_labels.csv")
df

,ID,YEAR,STATE,FIPSTATE,SC,CD,REDIST,ACEREGIO,AGE65,BANK,...,VABEDS,VETERANS,WHLRETL,PREVID,PREVPARTY,PREVCANDVO,PREVTOTVO,PARTY,CANDIDATEVOTES,TOTALVOTES
0,CT-1-1978,1978,CT,9,1,1,,1,52703,8705,...,178,61883.0,42454,CT-1-1976,NaN,NaN,NaN,democrat,102749,172564
1,CT-2-1978,1978,CT,9,1,2,,1,44350,8705,...,723,57185.0,33055,CT-2-1976,NaN,NaN,NaN,democrat,116624,166814
2,CT-3-1978,1978,CT,9,1,3,,1,50047,8705,...,0,62475.0,41978,CT-3-1976,NaN,NaN,NaN,democrat,96830,166587
3,CT-4-1978,1978,CT,9,1,4,,1,50841,8705,...,0,61641.0,42188,CT-4-1976,NaN,NaN,NaN,republican,83990,143919
4,CT-5-1978,1978,CT,9,1,5,,1,47411,8705,...,0,61394.0,35920,CT-5-1976,NaN,NaN,NaN,democrat,96738,184913
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259,WA-7-1996,1996,WA,53,73,7,0,17,79594,41400,...,379,628943.0,60552,WA-7-1994,democrat,148353.0,197444.0,democrat,209753,259094
4260,WA-8-1996,1996,WA,53,73,8,0,17,43283,41400,...,0,628943.0,60076,WA-8-1994,republican,140409.0,184574.0,republican,170691,261031
4261,WA-9-1996,1996,WA,53,73,9,0,17,52223,41400,...,203,628943.0,61926,WA-9-1994,republican,77833.0,150284.0,democrat,105236,209867
4262,HI-1-1996,1996,HI,15,82,1,0,19,69204,22300,...,0,112011.0,66412,HI-1-1994,democrat,94754.0,176706.0,democrat,86732,172206
4263,HI-2-1996,1996,HI,15,82,2,0,19,55473,22300,...,0,112011.0,55215,HI-2-1994,democrat,124431.0,177396.0,democrat,109178,180963

## 2. Data cleaning

In [2]:
df = df[df["date"].isin(["2020-02-01","2020-02-15","2020-03-01","2020-03-15",
                         "2020-04-01","2020-04-15","2020-05-01","2020-05-15",
                         "2020-06-01","2020-06-15","2020-07-01","2020-07-15"])]
df = df[-df["location"].isin(["World","International"])]
df = df[["location","date","total_cases","new_cases","total_deaths","new_deaths",
         "total_cases_per_million","new_cases_per_million",
         "total_deaths_per_million","new_deaths_per_million",
         "population","population_density","life_expectancy"]]
df = df.dropna()
df

,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,total_deaths_per_million,new_deaths_per_million,population,population_density,life_expectancy
32,Afghanistan,2020-02-01,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0,38928341.0,54.422,64.83
46,Afghanistan,2020-02-15,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0,38928341.0,54.422,64.83
61,Afghanistan,2020-03-01,1.0,0.0,0.0,0.0,0.026,0.000,0.000,0.0,38928341.0,54.422,64.83
65,Afghanistan,2020-03-15,10.0,3.0,0.0,0.0,0.257,0.077,0.000,0.0,38928341.0,54.422,64.83
82,Afghanistan,2020-04-01,166.0,25.0,4.0,0.0,4.264,0.642,0.103,0.0,38928341.0,54.422,64.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30952,Zimbabwe,2020-05-15,37.0,0.0,4.0,0.0,2.489,0.000,0.269,0.0,14862927.0,42.729,61.49
30969,Zimbabwe,2020-06-01,178.0,4.0,4.0,0.0,11.976,0.269,0.269,0.0,14862927.0,42.729,61.49
30983,Zimbabwe,2020-06-15,383.0,27.0,4.0,0.0,25.769,1.817,0.269,0.0,14862927.0,42.729,61.49
30999,Zimbabwe,2020-07-01,591.0,17.0,7.0,0.0,39.763,1.144,0.471,0.0,14862927.0,42.729,61.49
31013,Zimbabwe,2020-07-15,1034.0,0.0,19.0,0.0,69.569,0.000,1.278,0.0,14862927.0,42.729,61.49

Select the locations that have a complete set of data (12 dates, from 02/01 to 07/15).

In [3]:
locations = []
for location in set(df["location"]):
    if len(set(df[df["location"] == location]["date"])) == 12:
        locations.append(location)
df = df[df["location"].isin(locations)]
print("number of locations", len(locations))
df

number of locations 62

,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,total_deaths_per_million,new_deaths_per_million,population,population_density,life_expectancy
32,Afghanistan,2020-02-01,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0,38928341.0,54.422,64.83
46,Afghanistan,2020-02-15,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0,38928341.0,54.422,64.83
61,Afghanistan,2020-03-01,1.0,0.0,0.0,0.0,0.026,0.000,0.000,0.0,38928341.0,54.422,64.83
65,Afghanistan,2020-03-15,10.0,3.0,0.0,0.0,0.257,0.077,0.000,0.0,38928341.0,54.422,64.83
82,Afghanistan,2020-04-01,166.0,25.0,4.0,0.0,4.264,0.642,0.103,0.0,38928341.0,54.422,64.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30522,Vietnam,2020-05-15,312.0,24.0,0.0,0.0,3.205,0.247,0.000,0.0,97338583.0,308.127,75.40
30539,Vietnam,2020-06-01,328.0,1.0,0.0,0.0,3.370,0.010,0.000,0.0,97338583.0,308.127,75.40
30553,Vietnam,2020-06-15,334.0,0.0,0.0,0.0,3.431,0.000,0.000,0.0,97338583.0,308.127,75.40
30569,Vietnam,2020-07-01,355.0,0.0,0.0,0.0,3.647,0.000,0.000,0.0,97338583.0,308.127,75.40
30583,Vietnam,2020-07-15,373.0,0.0,0.0,0.0,3.832,0.000,0.000,0.0,97338583.0,308.127,75.40

## 3. Classification

[Test:] Can we predict whether "new_cases" on 07/15 is bigger than "new_cases" on 07/01 based on historical data (8 dates: 03/15, 04/01, 04/15, 05/01, 05/15, 06/01, 06/15, 07/01)?

[Train:] "new_cases" **bigger?** as label on 07/01 (than 06/15), 06/15 (than 06/01), 06/01 (than 05/15).
* If label date = 07/01, Features: 8 dates: 03/01, 03/15, 04/01, 04/15, 05/01, 05/15, 06/01, 06/15.
* If label date = 06/15, Features: 8 dates: 02/15, 03/01, 03/15, 04/01, 04/15, 05/01, 05/15, 06/01.
* If label date = 06/01, Features: 8 dates: 02/01, 02/15, 03/01, 03/15, 04/01, 04/15, 05/01, 05/15.

In [4]:
feature_names = ["total_cases","new_cases","total_deaths","new_deaths",
         "total_cases_per_million","new_cases_per_million",
         "total_deaths_per_million","new_deaths_per_million",
         "population","population_density","life_expectancy"]

In [5]:
import numpy as np

X_train, y_train = [], []
X_test, y_test = [], []

for location in sorted(set(df["location"])):
    temp = df[df["location"] == location]
    
    newnum = temp[temp["date"] == "2020-07-15"]["new_cases"].to_numpy()[0]
    oldnum = temp[temp["date"] == "2020-07-01"]["new_cases"].to_numpy()[0]
    label = 1 if newnum > oldnum else 0
    features = temp[temp["date"].isin(["2020-03-15", "2020-04-01",
                            "2020-04-15", "2020-05-01",
                            "2020-05-15", "2020-06-01",
                            "2020-06-15", "2020-07-01"])][feature_names].values.flatten()
    X_test.append(features)
    y_test.append(label)
    
    newnum = temp[temp["date"] == "2020-07-01"]["new_cases"].to_numpy()[0]
    oldnum = temp[temp["date"] == "2020-06-15"]["new_cases"].to_numpy()[0]
    label = 1 if newnum > oldnum else 0
    features = temp[temp["date"].isin(["2020-03-01", "2020-03-15",
                            "2020-04-01", "2020-04-15",
                            "2020-05-01", "2020-05-15",
                            "2020-06-01", "2020-06-15"])][feature_names].values.flatten()
    X_train.append(features)
    y_train.append(label)
    
    newnum = temp[temp["date"] == "2020-06-15"]["new_cases"].to_numpy()[0]
    oldnum = temp[temp["date"] == "2020-06-01"]["new_cases"].to_numpy()[0]
    label = 1 if newnum > oldnum else 0
    features = temp[temp["date"].isin(["2020-02-15", "2020-03-01",
                            "2020-03-15", "2020-04-01",
                            "2020-04-15", "2020-05-01",
                            "2020-05-15", "2020-06-01"])][feature_names].values.flatten()
    X_train.append(features)
    y_train.append(label)

    newnum = temp[temp["date"] == "2020-06-01"]["new_cases"].to_numpy()[0]
    oldnum = temp[temp["date"] == "2020-05-15"]["new_cases"].to_numpy()[0]
    label = 1 if newnum > oldnum else 0
    features = temp[temp["date"].isin(["2020-02-01", "2020-02-15",
                            "2020-03-01", "2020-03-15",
                            "2020-04-01", "2020-04-15",
                            "2020-05-01", "2020-05-15"])][feature_names].values.flatten()
    X_train.append(features)
    y_train.append(label)

X_train, X_test = np.array(X_train), np.array(X_test)

print("X_train.shape", X_train.shape)
print("y_train.shape", len(y_train), "#positives (more cases):", sum(y_train))
print("X_test.shape", X_test.shape)
print("y_test.shape", len(y_test), "#positives (more cases):", sum(y_test))

X_train.shape (186, 88)
y_train.shape 186 #positives (more cases): 89
X_test.shape (62, 88)
y_test.shape 62 #positives (more cases): 35

In [6]:
from sklearn import metrics

from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neural_network import MLPClassifier

clf_knn = KNeighborsClassifier()
clf_id3 = tree.DecisionTreeClassifier(criterion="entropy", max_depth=2)
clf_id3_overfit = tree.DecisionTreeClassifier(criterion="entropy")
clf_cart = tree.DecisionTreeClassifier(max_depth=2)
clf_bayes = GaussianNB()
clf_rbf = SVC()
clf_forest = RandomForestClassifier()
clf_boost = AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=2), random_state=21)
clf_mlp = MLPClassifier(hidden_layer_sizes=(50,50,), max_iter=1000, tol=0.001, random_state=42)

clf_knn.fit(X_train, y_train)
clf_id3.fit(X_train, y_train)
clf_id3_overfit.fit(X_train, y_train)
clf_cart.fit(X_train, y_train)
clf_bayes.fit(X_train, y_train)
clf_rbf.fit(X_train, y_train)
clf_forest.fit(X_train, y_train)
clf_boost.fit(X_train, y_train)
clf_mlp.fit(X_train, y_train)

print("Accuracy:")
print("- KNN:", metrics.accuracy_score(y_test, clf_knn.predict(X_test)))
print("- ID3:", metrics.accuracy_score(y_test, clf_id3.predict(X_test)))
print("- ID3 (overfitting):", metrics.accuracy_score(y_test, clf_id3_overfit.predict(X_test)))
print("- CART:", metrics.accuracy_score(y_test, clf_cart.predict(X_test)))
print("- Naive Bayes:", metrics.accuracy_score(y_test, clf_bayes.predict(X_test)))
print("- RBF Kernel SVC:", metrics.accuracy_score(y_test, clf_rbf.predict(X_test)))
print("- Random Forest:", metrics.accuracy_score(y_test, clf_forest.predict(X_test)))
print("- AdaBoost:", metrics.accuracy_score(y_test, clf_boost.predict(X_test)))
print("- MLP:", metrics.accuracy_score(y_test, clf_mlp.predict(X_test)))

Accuracy:
- KNN: 0.5161290322580645
- ID3: 0.6129032258064516
- ID3 (overfitting): 0.5806451612903226
- CART: 0.6129032258064516
- Naive Bayes: 0.532258064516129
- RBF Kernel SVC: 0.5
- Random Forest: 0.4838709677419355
- AdaBoost: 0.6451612903225806
- MLP: 0.6129032258064516

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

## 4. Regression

[Test:] Can we predict "new_cases" on 07/15 based on historical data (8 dates: 03/15, 04/01, 04/15, 05/01, 05/15, 06/01, 06/15, 07/01)?

[Train:] "new_cases" as label on 07/01, 06/15, 06/01.
* If label date = 07/01, Features: 8 dates: 03/01, 03/15, 04/01, 04/15, 05/01, 05/15, 06/01, 06/15.
* If label date = 06/15, Features: 8 dates: 02/15, 03/01, 03/15, 04/01, 04/15, 05/01, 05/15, 06/01.
* If label date = 06/01, Features: 8 dates: 02/01, 02/15, 03/01, 03/15, 04/01, 04/15, 05/01, 05/15.

In [7]:
y_train, y_test = [], []

for location in sorted(set(df["location"])):
    temp = df[df["location"] == location]
    
    newnum = temp[temp["date"] == "2020-07-15"]["new_cases"].to_numpy()[0]
    y_test.append(newnum+1) # --> for log_error
    
    newnum = temp[temp["date"] == "2020-07-01"]["new_cases"].to_numpy()[0]
    y_train.append(newnum+1)
    
    newnum = temp[temp["date"] == "2020-06-15"]["new_cases"].to_numpy()[0]
    y_train.append(newnum+1)

    newnum = temp[temp["date"] == "2020-06-01"]["new_cases"].to_numpy()[0]
    y_train.append(newnum+1)

print("y_train.shape", len(y_train), "min:", min(y_train), "max:", max(y_test))
print("y_test.shape", len(y_test), "min:", min(y_test), "max:", max(y_test))

y_train.shape 186 min: 1.0 max: 68519.0
y_test.shape 62 min: 1.0 max: 68519.0

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import BayesianRidge
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.neural_network import MLPRegressor

reg_lr = LinearRegression()
reg_knn = KNeighborsRegressor()
reg_cart = tree.DecisionTreeRegressor()
reg_bayes = BayesianRidge()
reg_rbf = SVR()
reg_forest = RandomForestRegressor(random_state=42)
reg_boost = AdaBoostRegressor(random_state=42)
reg_mlp = MLPRegressor(random_state=42)

reg_lr.fit(X_train, y_train)
reg_knn.fit(X_train, y_train)
reg_cart.fit(X_train, y_train)
reg_bayes.fit(X_train, y_train)
reg_rbf.fit(X_train, y_train)
reg_forest.fit(X_train, y_train)
reg_boost.fit(X_train, y_train)
reg_mlp.fit(X_train, y_train)

print("MSLE:")
print("- Linear Regression:", metrics.mean_squared_log_error(y_test, np.absolute(reg_lr.predict(X_test))))
print("- KNN:", metrics.mean_squared_log_error(y_test, np.absolute(reg_knn.predict(X_test))))
print("- CART:", metrics.mean_squared_log_error(y_test, np.absolute(reg_cart.predict(X_test))))
print("- Bayesian Ridge:", metrics.mean_squared_log_error(y_test, np.absolute(reg_bayes.predict(X_test))))
print("- RBF Kernel SVR:", metrics.mean_squared_log_error(y_test, np.absolute(reg_rbf.predict(X_test))))
print("- Random Forest:", metrics.mean_squared_log_error(y_test, np.absolute(reg_forest.predict(X_test))))
print("- AdaBoost:", metrics.mean_squared_log_error(y_test, np.absolute(reg_boost.predict(X_test))))
print("- MLP:", metrics.mean_squared_log_error(y_test, np.absolute(reg_mlp.predict(X_test))))

MSLE:
- Linear Regression: 17.86119446978422
- KNN: 4.0882677615894245
- CART: 1.9722927424175254
- Bayesian Ridge: 6.2328763007592975
- RBF Kernel SVR: 7.184319019445448
- Random Forest: 1.7714774728876155
- AdaBoost: 8.00575351887432
- MLP: 20.123937393917917